name: Reusable build with analyze

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      analyze:
        required: true
        type: boolean
    secrets:
      my-secret:
        required: true
      github-token:
        required: true

jobs:
  build and analyze:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      - name: Run a multi-line script
        env:
          S1: ${{ secrets.my-secret }}
          GITHUB_TOKEN: ${{ secrets.github-token }}
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo secret S1: ${S1}
          echo secret GITHUB_TOKEN: ${GITHUB_TOKEN}
          if [ -z "${S1}" ]; then echo "secret var is Unset!"; else echo "secret var is set"; fi
          echo README:
          cat README.md
